get compare working with run-noop

diff --git a/libexec/run-noop b/libexec/run-noop
--- a/libexec/run-noop
+++ b/libexec/run-noop
@@ -18,6 +18,28 @@ DEFINE_boolean make "$FLAGS_FALSE" "Run make"
 
 # entry point
 function main {
+  case "$#" in
+    0)
+      logger_fatal "missing DIR VERSION DNA"
+      exit 1
+      ;;
+    1)
+      logger_fatal "missing VERSION DNA"
+      exit 1
+      ;;
+    2)
+      logger_fatal "missing DNA"
+      exit 1
+      ;;
+    3)
+      true
+      ;;
+    *)
+      logger_fatal "too many args"
+      exit 1
+      ;;
+  esac
+
   local pth_workarea="$1"; shift
   local ver_repo="$1"; shift
 
@@ -41,12 +63,7 @@ function main {
     make
   fi
 
-  local cmd_chef_local="bundle exec chef-local"
-  if [[ -x "bin/chef-local" ]]; then
-    cmd_chef_local="bin/chef-local"
-  fi
-
-  $cmd_chef_local --noop -c etc/chef/solo.rb -j $pth_rna > "var/chef/reports/chef.log"
+  bundle exec chef-local --noop -c etc/chef/solo.rb -j $pth_rna > "var/chef/reports/chef.log"
   (set +f; $shome/libexec/sanitize node "var/chef/reports/"chef*.json > "chef.json")
   $shome/libexec/sanitize log "var/chef/reports/chef.log" > "chef.log"
 }
